spring.application.name=orquestador


server.port=8087
server.address=0.0.0.0

spring.datasource.url=jdbc:oracle:thin:@192.168.56.101:1521/ORCL
spring.datasource.username=system
spring.datasource.password=oracle


spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.orm.jpa=DEBUG